services:
  discord-bot:
    build: .
    image: syntrel-discord-bot
    env_file:
      - .env
    volumes:
      - ./database:/bot/database
      - ./discord.log:/bot/discord.log
      - ./cogs/media/files:/bot/cogs/media/files

    # Alternatively you can set the environment variables as such:
    # /!\ The token shouldn't be written here, as this file is not ignored from Git /!\
    # environment:
    #   - PREFIX=YOUR_BOT_PREFIX_HERE
    #   - INVITE_LINK=YOUR_BOT_INVITE_LINK_HERE